apiVersion: batch/v1
kind: CronJob
metadata:
  name: fulltext-elastic-backup-job
  namespace: backup
spec:
  schedule: "00 15 * * *" # JST 00:00
  jobTemplate:
    spec:
      template:
        spec:
          # imagePullSecrets:
          # - name: regcred
          containers:
          - name: fulltext-elastic-backup
            image: c0a22100/doktor-elastic-backup:latest
            # image: ghcr.io/cdsl-research/mongo-backup:1.0
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: backup-config
            env:
            - name: ELASTICSEARCH_PORT
              value: "30301"
            - name: ELASTICSEARCH_OUTPUT
              value: "fulltext"
            volumeMounts:
            - name: nfs-volume
              mountPath: /backup
          volumes:
          - name: nfs-volume
            nfs:
              server: 192.168.100.3
              path: /volume1/doktor-dev-backup/
              readOnly: false 
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1