apiVersion: batch/v1
kind: CronJob
metadata:
  name: stats-mongo-backup-job
  namespace: backup
spec:
  schedule: "00 15 * * *" # JST 00:00
  jobTemplate:
    spec:
      template:
        spec:
          # imagePullSecrets:
          # - name: regcred
          containers:
          - name: stats-mongo-backup
            image: c0a22100/doktor-mongo-backup:latest
            # image: ghcr.io/cdsl-research/doktor-mongo-backup:1.0
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: backup-config
            env:
            - name: MONGO_PORT
              value: "30304" # 後でNodePortに固定するようにする
            - name: MONGO_DB
              value: "stats"
            - name: MONGO_COLLECTION
              value: "stats"
            - name: MONGO_OUTPUT
              value: "stats"
            volumeMounts:
            - name: nfs-volume
              mountPath: /backup
          volumes:
          - name: nfs-volume
            nfs:
              server: 192.168.100.3
              path: /volume1/doktor-dev-backup/
              # readOnly: false
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1