apiVersion: batch/v1
kind: CronJob
metadata:
  name: thumbnail-minio-backup-job
  namespace: backup
spec:
  schedule: "00 15 * * *" # JST 00:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: thumbnail-minio-backup
            image: ghcr.io/cdsl-research/doktor-minio-backup:v1.0
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: backup-common-config
            env:
            - name: MINIO_PORT
              value: "30305"
            - name: SERVICE_NAME
              value: "thumbnail"
            volumeMounts:
            - name: nfs-volume
              mountPath: /backup
          volumes:
          - name: nfs-volume
            nfs:
              server: 192.168.100.3
              path: /volume1/doktor-dev-backup/
              readOnly: false
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1